Added CDC-ECM interface to the TinyUSB component to enable Ethernet o…
ci4rail/esp-idf pull request #1
Opened 2021-06-07 14:03 UTC by FranziskaKnoedtel

Added CDC-ECM interface to the TinyUSB component to enable Ethernet over USB.
Added example (examples/peripherals/usb/tusb_cdc_ecm) to demonstrate how to use the new API.
Added simple tcp_client to test the connection.

2021-06-07 19:16 UTC, KlausPopp requested changes
Almost perfect! But consider the few major remarks.

2021-06-07 19:16 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    vTaskDelay(pdMS_TO_TICKS(10));
MAJOR: The delay may have massive impact on performance and reliability. What happens if more than one frame has arrived in 10ms? Then we will loose the intermediate frames.
Consider using a queue, which is filled by tud_network_recv_cb and drained by service_traffic. Or (if possible), call ethernet input directly from tud_network_recv_cb.

2021-06-07 19:16 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    netif->hwaddr[5] ^= 0x01;
Can be problematic. This means that the host's MAC address is computed from the internal MAC address. 
Is it guaranteed that the host's MAC will never be used by another ESP32 with a different serial number?
Is it possible to let the host assign a random MAC address?

2021-06-07 19:16 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +      printf("%02x:", cfg.mac_address[i]);
Remove Trailing ":" after last byte

2021-06-07 19:16 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    while (!netif_is_up(&netif_data));
This may block forever. Consider adding a timeout. 
Who brings the netif up? Is it done by another task? If so, is it guaranteed that this task has a higher priority?

2021-06-07 19:16 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_tasks.c
> +        vTaskDelay(pdMS_TO_TICKS(10));
Pretty sure that this modification is not accepted. Why is this delay necessary?
Might break other USB drivers.

2021-06-08 13:37 UTC, FranziskaKnoedtel commented on components/tinyusb/additions/src/descriptors_control.c
> +static uint8_t mac_address[6];
The MAC Address (of the host NIC) is requested by the usb driver with the callback tud_descriptor_string_cb(). If the MAC Address shall be returned, the index, which was given by TUD_CDC_ECM_DESCRIPTOR() (STRID_MAC), is passed to this callback. That is why, the MAC Address has to be declared in this file too.

2021-06-08 14:20 UTC, FranziskaKnoedtel commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    while (!netif_is_up(&netif_data));
It is set in the same thread before. It is just a flag and no parallel process. I replaced the while loop with an if query.

2021-06-09 06:09 UTC, KlausPopp requested changes

2021-06-09 06:09 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +      rx_frame_buffer.frame[rx_frame_buffer.write_idx] = p;
Check missing for queue full

2021-06-09 06:09 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    if(xSemaphoreTake(rx_event, pdMS_TO_TICKS(10)))
Why is the timeout needed?

2021-06-09 06:09 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    rx_frame_buffer.frame[rx_frame_buffer.read_idx] = NULL;
Where is the buffer released? (pbuf_free)

2021-06-09 06:09 UTC, KlausPopp commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    if(xSemaphoreTake(rx_event, pdMS_TO_TICKS(10)))
1) The semaphore handling is not correct, that's probably the reason why you need the timeout. Let's discuss
2) Why is only one frame handled in service_traffic? Better handle all received frames in service_traffic

2021-06-09 07:23 UTC, FranziskaKnoedtel commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +      rx_frame_buffer.frame[rx_frame_buffer.write_idx] = p;
It is checked in line 187.

2021-06-09 07:44 UTC, FranziskaKnoedtel commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    rx_frame_buffer.frame[rx_frame_buffer.read_idx] = NULL;
It is freed in ethernet_input():
`  /* This means the pbuf is freed or consumed,
     so the caller doesn't have to free it again */`

2021-06-09 08:20 UTC, FranziskaKnoedtel commented on components/tinyusb/additions/src/tusb_cdc_ecm.c
> +    if(xSemaphoreTake(rx_event, pdMS_TO_TICKS(10)))
Timeout was to schedule the function sys_check_timeouts() even if no frame was received. But as we are running with freertos, this function is not needed to be called.

2021-06-09 09:03 UTC, KlausPopp approved these changes

2021-06-11 12:50 UTC, merged